version: '3'


services:
  nats_server:
    image: nats:latest
    ports:
      - "8222:8222" # Monitoring port

  client-gateway:
    build: ./client-gateway
    ports:
      - "${CLIENT_GATEWAY_PORT}:3000"
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: pnpm run start:dev
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats_server:4222
      - CHOKIDAR_USEPOLLING=true

  products-ms:
    build: ./products-ms
    volumes:
      - ./products-ms/src:/usr/src/app/src
    command: pnpm run start:dev
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats_server:4222
      - DATABASE_URL=file:./dev.db
      - CHOKIDAR_USEPOLLING=true

  orders-ms:
    depends_on:
      - orders-db
    build: ./orders-ms
    volumes:
      - ./orders-ms/src:/usr/src/app/src
    command: pnpm run start:dev
    environment:
      - PORT=3002
      - NATS_SERVERS=nats://nats_server:4222
      - DATABASE_URL=postgresql://postgres:123456@orders-db:5432/ordersdb?schema=public
      - CHOKIDAR_USEPOLLING=true


  orders-db:
    image: postgres:16.2
    container_name: orders_database
    restart: always
    volumes:
      - ./orders-ms/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=ordersdb
    ports:
      - 5432:5432