apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: order-ms
  name: order-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: order-ms
    spec:
      containers:
        - image: europe-southwest1-docker.pkg.dev/tienda-microservices-459210/docker-registry/orders-ms
          name: orders-mss
          env:
            - name: PORT
              value: "3000"
            - name: NATS_SERVERS
              value: "nats://nats"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: orders-secrets
                  key: database_url
          resources: {}
status: {}
